---
name: Run Linter
on: [push]

jobs:
  linting:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Install pylint
        run: sudo apt-get -y install pylint

      - name: Lint Code
        run: pylint murphybot.py
