---
name: Run Linter
on: [push]

jobs:
  linting:
    name: Lint and Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repo
      - name: Checkout
        uses: actions/checkout@v2

      # Use Python3.6 environment
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      # Install pylint(can test with flake8 and others)
      - name: Install pylint
        run: sudo apt-get -y install pylint

      # Run the linter
      #- name: Lint Code
      #  run: pylint *.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::942158337222:role/gk_lambda_deploy_role
          role-duration-seconds: 900

      - name: Build in Virtual Environment
        run: |
          python -m pip install virtualenv
          virtualenv murphybot
          source murphybot/bin/activate
          cd murphybot
          pip install requests pymysql boto3
          chmod -R 755 .
          deactivate
          zip -r ../murphybot.zip ./
          cd ..

#      - name: Build Lambda Artifact
#        run: |
